import { useState } from 'react';
import type { PageProps } from './types';

export function PrivacyPage({ locale, privacy, setPrivacy, api, selected, conversations, summary, snapshot, refresh }: PageProps) {
  const [confirm, setConfirm] = useState(false); const [saved, setSaved] = useState(false); const zh = locale === 'zh';
  const save = async () => { const next = await api.updatePrivacy(privacy); setPrivacy(next); setSaved(true); };
  const remove = async () => { if (!selected) return; if (!confirm) { setConfirm(true); return; } await api.deleteSession(selected.sessionId); setConfirm(false); refresh(); };
  const messages = conversations.reduce((sum,item)=>sum+item.messages.length,0);
  return <div className="local-data-workspace"><section className="local-inventory"><span>LOCAL SQLITE</span><h2>{zh ? '本机到底保存了什么' : 'What is stored locally'}</h2><div className="inventory-grid"><Inventory value={summary.projects} label={zh?'项目':'Projects'} /><Inventory value={summary.sessions} label={zh?'会话':'Sessions'} /><Inventory value={conversations.length} label={zh?'模型请求':'Requests'} /><Inventory value={messages} label={zh?'完整消息':'Messages'} /><Inventory value={snapshot.memories.active+snapshot.memories.candidate+snapshot.memories.disabled} label={zh?'项目记忆':'Memories'} /><Inventory value={summary.events} label={zh?'引导证据':'Guidance evidence'} /></div><p>{zh ? '数据库位于操作系统的 AgentDoctor 应用数据目录；传输认证凭证不会写入表中。' : 'The database stays in the OS AgentDoctor app-data directory; transport credentials are never stored.'}</p></section><div className="privacy-grid"><section><span>{zh?'保留策略':'RETENTION'}</span><h2>{zh ? '采集与自动清理' : 'Capture and retention'}</h2><label><input type="checkbox" checked={privacy.capturePrompts} onChange={(event) => setPrivacy({ ...privacy, capturePrompts: event.target.checked })} />{zh ? '保存完整对话消息' : 'Store complete conversation messages'}</label><label>{zh ? '自动清理天数' : 'Retention days'}<input aria-label={zh ? '自动清理天数' : 'Retention days'} type="number" min="1" max="3650" value={privacy.retentionDays} onChange={(event) => setPrivacy({ ...privacy, retentionDays: Number(event.target.value) })} /></label><button className="primary-action" onClick={save}>{zh ? '保存到本地' : 'Save locally'}</button>{saved && <p role="status">{zh ? '设置已保存。' : 'Settings saved.'}</p>}</section><section className="danger-zone"><span>CONTROL</span><h2>{zh ? '删除当前会话' : 'Delete current session'}</h2><p>{selected ? selected.sessionId : (zh ? '当前没有可删除的会话。' : 'No session is selected.')}</p><button disabled={!selected} onClick={remove}>{confirm ? (zh ? '再次点击，永久删除' : 'Click again to delete permanently') : (zh ? '删除这条会话' : 'Delete this session')}</button></section></div></div>;
}
function Inventory({value,label}:{value:number;label:string}){return <article><strong>{value}</strong><span>{label}</span></article>}
