import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { App } from '../src/App';
import type { DashboardAPI } from '../src/api';

afterEach(() => { cleanup(); window.localStorage.clear(); });
const conversation = { id:'request-1', sessionId:'session-42', projectId:'project', client:{name:'codex',version:'1'}, model:{displayName:'gpt-test'}, protocol:'openai', method:'POST', path:'/v1/responses', statusCode:200, startedAt:'2026-08-14T10:00:00Z', completedAt:'2026-08-14T10:00:01Z', firstByteMs:120, durationMs:900, usage:{inputTokens:42,outputTokens:18,cachedTokens:10,reasoningTokens:3,precision:'exact' as const,provenance:'provider'}, cost:{currency:'USD',precision:'unavailable' as const,provenance:'no-catalog'}, messages:[{id:'m1',requestId:'request-1',sequence:0,role:'user' as const,content:'请完整分析这个问题',createdAt:'2026-08-14T10:00:00Z'},{id:'m2',requestId:'request-1',sequence:1,role:'assistant' as const,content:'这是完整模型回复',createdAt:'2026-08-14T10:00:01Z'}] };
const api: DashboardAPI = {
  loadSummary: vi.fn(async()=>({projects:2,sessions:3,activeSessions:1,events:12,precision:{exact:8,estimated:3,unavailable:1}})),
  loadSnapshot: vi.fn(async()=>({sessions:[],costs:{currency:'USD',exactMicros:0,estimatedMicros:0,unavailable:1},memories:{active:4,candidate:2,disabled:1},trends:[{date:'2026-08-14',sessions:2,events:9}],comparisonCount:0})),
  loadPrivacy: vi.fn(async()=>({capturePrompts:true,captureFileContents:false,retentionDays:30})), updatePrivacy: vi.fn(async(value)=>value), loadSession:vi.fn(async()=>({sessionId:'session-42',events:[]})),
  loadConversations:vi.fn(async()=>[conversation]), loadConversation:vi.fn(async()=>conversation), loadConnections:vi.fn(async()=>[{key:'codex',displayName:'Codex',detected:true,state:'active' as const,capability:'proxy',detail:'正在采集',updatedAt:'2026-08-14T10:00:00Z'}]),
  loadLiveAnalysis:vi.fn(async()=>({projectId:'project-current',requests:12,activeSessions:1,inputTokens:49_000_000,outputTokens:795_296,cachedTokens:10_000_000,reasoningTokens:3,exactCostMicros:0,estimatedCostMicros:0,unknownCostCount:1,averageLatencyMs:359_832,failedRequests:2,toolCalls:18,tokensPerRequest:4_149_608,cacheHitRate:20.08,healthScore:64,summary:'当前项目可以继续工作，但失败率和上下文消耗偏高。',findings:[{id:'failure-rate',severity:'high' as const,title:'失败请求偏多',description:'12 次请求中有 2 次失败。',evidence:'失败率 16.7%',recommendation:'先处理最近一次失败，再继续扩大任务范围。'},{id:'latency',severity:'medium' as const,title:'响应耗时偏高',description:'平均响应接近 6 分钟。',evidence:'平均 5 分 59.8 秒',recommendation:'拆分长任务并减少重复上下文。'}],limitations:[]})), deleteSession:vi.fn(async()=>undefined),
};

describe('Chinese-first live dashboard',()=>{
  it('prioritizes project diagnosis and keeps raw conversation behind disclosure',async()=>{render(<App api={api}/>);await waitFor(()=>expect(screen.getByText('项目分析驾驶舱')).toBeVisible());expect(screen.getByText('当前项目可以继续工作，但失败率和上下文消耗偏高。')).toBeVisible();expect(screen.getByText('失败请求偏多')).toBeVisible();expect(screen.getByText('4979.5 万')).toBeVisible();expect(screen.getAllByText('5 分 59.8 秒').length).toBeGreaterThan(0);expect(screen.queryByText('请完整分析这个问题')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'查看原始对话'}));expect(screen.getByText('请完整分析这个问题')).toBeVisible();expect(screen.getByText('这是完整模型回复')).toBeVisible();});
  it('keeps all eight pages useful',async()=>{render(<App api={api}/>);await screen.findByText('项目分析驾驶舱');for(const label of ['完整对话','用量与费用','项目记忆','任务对比','效率趋势','编辑器连接','本地数据']){fireEvent.click(screen.getByRole('button',{name:label}));expect(screen.getByRole('heading',{name:label})).toBeVisible();}});
  it('renders Chinese by default and persists an explicit language change',async()=>{render(<App api={api}/>);await screen.findByText('项目分析驾驶舱');fireEvent.click(screen.getByRole('button',{name:'English'}));expect(window.localStorage.getItem('agent-doctor-locale')).toBe('en');expect(screen.getByRole('heading',{name:/Project analysis cockpit/})).toBeVisible();});
  it('requires a second action before deleting a session',async()=>{render(<App api={api}/>);await screen.findByText('项目分析驾驶舱');fireEvent.click(screen.getByRole('button',{name:'本地数据'}));fireEvent.click(screen.getByRole('button',{name:'删除这条会话'}));expect(api.deleteSession).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'再次点击，永久删除'}));await waitFor(()=>expect(api.deleteSession).toHaveBeenCalledWith('session-42'));});
});
